### ISSUE TITLE
Javascript - Investigate why `npx typescript` fails on certain machines whereas `npx tsc` succeeds

### ISSUE THREAD

**Issue by lugehorsam** [heroiclabs/nakama-js#102]

**Comment by orta** [comment]
`npx` has somewhat indeterminate behavior depending on your npm version, globals and your node_modules. For example;

npm 7:
 - no node_modules, install and run the [npm module tsc](https://www.npmjs.com/package/tsc) which I recently deprecated with error messages
 -  no node_modules but has typescript globally installed (unlikely on CI) then run the global version of `tsc`
 - node_modules installed, with TypeScript in the deps: run `tsc` correctly

npm 8 should bail on the top state asking if you want to install the npm module `tsc`. 

Personally, I'd recommend `yarn` or `pnpm` which doesn't have this sort of confusing UX

**Comment by jackunion** [comment]
@lugehorsam this one is related to https://github.com/heroiclabs/nakama-js/issues/138

Maybe could be closed since `npx typescript` has been updated to `npx tsc`?
