### ISSUE TITLE
Errors not decoded (unreadable)

### ISSUE THREAD

**Issue by Rojoss** [heroiclabs/nakama-js#104]
I'm trying to read errors sent by our backend (Golang) in the client but I'm unable to do so.
The `error.body` is a `ReadableStream` which contains an `Uint8Array`.
I have no clue how to decode these error messages and it's quite annoying not being able to see errors on the client.
I asked on Gitter and was told to make an issue because this SDK should handle the decoding of errors.

I also noticed `error.type` is `cors`, not sure why that is?

**Backend:** `github.com/heroiclabs/nakama-common v1.18.0`
**Frontend:** `"@heroiclabs/nakama-js": "^2.3.0"`

This is the error object:
![image](https://user-images.githubusercontent.com/1093861/139690834-b21cbee4-3474-4bcd-ad1e-75e6685dcbf1.png)

Here is the code in case I'm just doing something wrong
```typescript
backendSDK.sendRPC("ADD_BOT_MESSAGE", xxx).catch((err) =>
		{
			console.error(err);
			if (err.body)
			{
				const reader: ReadableStreamDefaultReader<unknown> = (err.body as ReadableStream).getReader();
				reader.read().then((res) =>
				{
					console.error(res);
				}).catch((error: unknown) =>
				{
					console.error(error);
				});
			}
		});
```

```typescript
	public async sendRPC(id: string, msg: Uint8Array): Promise<Uint8Array>
	{
		const session: Session = await this.waitForConnection();
		return this._client.rpc(session, id, Networking.encode(msg)).then((response) =>
		{
			return Networking.decode(response.payload);
		});
	}
```

And on the backend I just return an error in RPC function
```go
func AddBotMessageRPC(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, payload string) (string, error) {
	userID, ok := ctx.Value(runtime.RUNTIME_CTX_USER_ID).(string)
	if !ok {
		return "", errors.New("invalid context, missing userID")
	}
	...
}
```

**Comment by lugehorsam** [comment]
Hey @Rojoss sorry for the late reply but for posterity you should use the `TextDecoder` and `TextEncoder` APIs  to convert UInt8Arrays from/to text and binary.
