### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by kraxarn** [heroiclabs/nakama-js#107]
nakama-js seems to stop working once a project uses ES6 modules. For example, simply doing this:
```js
import { Client } from "@heroiclabs/nakama-js"
const client = new Client()
```
Results in error:
```
import { Client } from "@heroiclabs/nakama-js";
         ^^^^^^
SyntaxError: Named export 'Client' not found. The requested module '@heroiclabs/nakama-js' is a CommonJS module, which may not support all module.exports as named exports.
```

It instead suggests importing it like:
```js
import nakama from "@heroiclabs/nakama-js"
const {Client} = nakama
```
But that instead throws another error:
```
   import nakama from "@heroiclabs/nakama-js"
          ^
   const { Client } = nakama
> 'default' is not exported by node_modules/@heroiclabs/nakama-js/dist/nakama-js.esm.js
```
Seems to be related to using TypeScript with `"module": "es2020"`.

**Comment by novabyte** [comment]
@kraxarn Thanks for the issue report. I'm not familiar with how the TypeScript `"module": "es2020"` affects a project built with ES6 modules. Can you suggest how it should be updated?

**Comment by kraxarn** [comment]
Tested the solution from #108 and can confirm it works fine now.
@bluwy Thank you for looking into this!

**Comment by andreavaccari** [comment]
@bluwy I have seen your name pop up so many times. Thank you for your contributions to Vite and Svelte!

Would you consider chiming in [here](https://github.com/samhh/fp-ts-std/issues/113) to help us figure out how to make this library work with SvelteKit?

Thank you!
