### ISSUE TITLE
TypeError: nakamajs.UsersFetchMessage is not a constructor

### ISSUE THREAD

**Issue by imilo** [heroiclabs/nakama-js#11]
According to the docs at `https://heroiclabs.com/docs/user-accounts/` I try to fetch users by ID.

But it seems there is no such function **UsersFetchMessage**, because the console error I get is:
`An error occured during session connection: TypeError: nakamajs.UsersFetchMessage is not a constructor`

**Comment by novabyte** [comment]
Hi @imilo. Looks like the docs are out of date with the latest update to the JavaScript. Thanks for letting me know. In the meantime what you'll want to use is `nakamajs.UsersFetchRequest`.

**Comment by novabyte** [comment]
@imilo This is sorted. The new client tests show usage for fetching batches of users.
