### ISSUE TITLE
Variables not passed on authentication

### ISSUE THREAD

**Issue by Rojoss** [heroiclabs/nakama-js#114]
When passing variables with authentication they don't get sent to the server.
This is due to the variables being added as a map in the body and the body then gets parsed to JSON.
But since it's a map this doesn't work so the client will always send an empty object for the variables.

Here you can see it if you add a breakpoint.
![image](https://user-images.githubusercontent.com/1093861/151869904-5666268b-cd19-4169-aecc-f661672164ea.png)

Wanted to make a MR but saw it was generated code so not sure what changes to make exactly but it would be great if this can be fixed because we want to restrict users with older clients from being able to authenticate.

**Comment by novabyte** [comment]
@Rojoss If you could open a merge request that would be great. We'll definitely make an adjustment to the code generator to ensure this passthrough happens correctly but a merge request would solve your immediate requirements quickly. I'll leave this issue open until the change is made to the code generator.
