### ISSUE TITLE
Javascript - Socket RPC never resolved or rejected when disconnected

### ISSUE THREAD

**Issue by Rojoss** [heroiclabs/nakama-js#117]
Hi, when making an RPC call while the network is turned off it never resolves or rejects.
I assume this is not the intended behavior right?

As you an see in this gif the first request works properly when connected.
Then I turn off the wifi and send another request, it's called but never resolved or rejected.
Even when I turn my wifi back on.

![ws_rpc_hangs](https://user-images.githubusercontent.com/1093861/154724279-402c7f23-fcb9-42d9-8842-b6611b464739.gif)

**Comment by lugehorsam** [comment]
Hey @Rojoss, thanks for finding this. It's definitely a problem and we'll look to fix it in the next release.

**Comment by jackunion** [comment]
@lugehorsam I can take take a look at this when I have time. What's the intended behaviour? Simply timing requests out or restoring them?

**Comment by lugehorsam** [comment]
Hey @jackunion and @Rojoss we've added socket heartbeating to the recent version of the client. This should resolve this issue. Let me know if it's still an issue.
