### ISSUE TITLE
How to build source

### ISSUE THREAD

**Issue by formatCvt** [heroiclabs/nakama-js#120]
I've trying to build sources on Mac and Linux and can't do this. 

Mac OS:
![изображение](https://user-images.githubusercontent.com/9342933/161376473-d3f9e836-a1eb-4758-894a-d88ecede016e.png)

Linux:
![изображение](https://user-images.githubusercontent.com/9342933/161376519-8de4352b-52f8-44f3-b87e-e1ed882e5780.png)
![изображение](https://user-images.githubusercontent.com/9342933/161376536-693b0a9c-3cec-4c2d-8235-2294750bff23.png)

How can i fix this?

**Comment by Rojoss** [comment]
Same thing here, also on Windows.
Must be related to the latest commit:
https://github.com/heroiclabs/nakama-js/commit/6de7fd5127dd65da61748763fb6aecf1e0adb899

**Comment by formatCvt** [comment]
thanks!
