### ISSUE TITLE
Version 2.4.0 published on NPM registry missing nakama-js.cjs.js file

### ISSUE THREAD

**Issue by maxbbb** [heroiclabs/nakama-js#129]
After upgrading to 2.4.0 I started receiving an error that the nakama-js package could not be resolved because it was missing one of the build files.

```
error While trying to resolve module '@heroiclabs/nakama-js' from file, the package 
'node_modules/@heroiclabs/nakama-js/package.json' was successfully found. 
However, this package itself specifies a 'main' module field that could not be resolved 
('node_modules/@heroiclabs/nakama-js/dist/nakama-js.cjs.js').
```

Comparing the 2.3.0 package to the 2.4.0 package it does look like the file is missing, and adding the file from the repo fixed the issue. I assume this is just a publishing error.

**Comment by MWFIAE** [comment]
@novabyte Got the same issue 🙏

**Comment by lugehorsam** [comment]
Very odd guys. I ran `npm pack` which simulates `npm publish` but produces a local tarball and it does include the common js file. I hate not knowing root cause but I am just try publishing again.

**Comment by lugehorsam** [comment]
@MWFIAE  @maxbbb  it appears to be a bug or unexpected behavior with the yarn workspaces API. I republished a new client using the raw npm commands: https://www.npmjs.com/package/@heroiclabs/nakama-js

Let me know how it goes.

**Comment by MWFIAE** [comment]
The new package includes the file and everything compiles again for me 🥳

**Comment by formatCvt** [comment]
Hi guys, same issue with `nakama-js-protobuf` package

![image](https://user-images.githubusercontent.com/9342933/173185475-988f595e-3b75-47a6-87d7-1759d3212654.png)

**Comment by lugehorsam** [comment]
hey @formatCvt I just published a new protobuf version. Could you try 1.2.1 instead?

**Comment by formatCvt** [comment]
everything is fine, thanks!
