### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by trueleowdeo** [heroiclabs/nakama-js#13]
This function is returning error net::ERR_CONNECTION_REFUSED

```
    nakamatest:function(){
        var client=new nakamajs.Client("defaultkey","127.0.0.1",7350);
        client.ssl=false;
        var sessionHandler=function(session)
        {
            console.log("Session: %o"+session);
            client.connect(session).then(function(session)
            {
                console.log("session connected");
                localStorage.nakamaToken=session.token;
            }).catch(function(error){
                console.log("an error occured during connection "+error);
            });
        }
        //login or register
        var errorHandler=function(error)
        {
            console.log(error);
        };
        var message= nakamajs.AuthenticateRequest.email("true@truth.org","truepassword");
        client.login(message).then(sessionHandler).catch(function (error)
        {
                client.register(message).then(sessionHandler).catch(errorHandler);
        });
    },

```
The docker container started without errors[see image]
https://ibb.co/cA4187

**Comment by mofirouz** [comment]
@trueleowdeo This isn't a bug on the nakama-js codebase. It's a misconfiguration on your client code / docker setup. If you examine the docker-compose, you can see the server address allocated to Nakama is not "127.0.0.1" - Please try either:
1. Checking to see if you can reach the embedded dashboard via your browser.
2. Changing the IP address in the code above to the server host.
3. Enabling host networking on your Nakama docker image run command.

**Comment by trueleowdeo** [comment]
@mofirouz Thanks so much. Please close the issue. It would be great if you mention the fact that the docker-machine ip may not be localhost in the js example code because many users,like myself are new to Nakama and Docker.
`//I hard coded the ip from running the command docker-machine ip instead of 127.0.0.1 and can now run examples successfully`

**Comment by mofirouz** [comment]
Glad that helped. Will make a note to update docs.
