### ISSUE TITLE
Build system update

### ISSUE THREAD

**Issue by lugehorsam** [heroiclabs/nakama-js#138]
Update to Yarn Version 3

Also investigate why `npx typescript` doesn't work on some machines -- and we should probably be using `yarn dlx` instead of `npx` so we don't bypass Yarn.

Also, shouldn't it be `npx tsc` instead of `npx typescript`?

**Comment by jackunion** [comment]
@lugehorsam still need help on this? I can see the build command has been updated to `tsc` already.

**Comment by lugehorsam** [comment]
Hey @jackunion thanks for catching, yes I think this is all sorted now thanks to @tomglenn. We no longer use Yarn.
