### ISSUE TITLE
connect method raises "Can't find variable: URLSearchParams" in React Native

### ISSUE THREAD

**Issue by gmertk** [heroiclabs/nakama-js#14]
Hi folks, 
I'm trying to use this lib in a React Native project. Calling `connect`:

```
    this.client
      .connect(session)
      .then(function(session) {
        console.log("Session connected.");

        // This returns a promise - if it fails, we are catching the error in the `error` callback below
        return AsyncStorage.setItem("@MyApp:nakamajsToken", session.token);
      })
```

raises "An error occured: %o [ReferenceError: Can't find variable: URLSearchParams]" due to https://github.com/heroiclabs/nakama-js/blob/master/src/Client.js#L61

**Comment by novabyte** [comment]
Thanks @gmertk. Didn't realise URLSearchParams is not available with React Native. Can you open a PR?

**Comment by gmertk** [comment]
It seems like the variable searchParams isn't used at all. The url is already constructed with the other variables on https://github.com/heroiclabs/nakama-js/blob/master/src/Client.js#L67 I'll send a PR to remove it. Does it sound good to you?

**Comment by novabyte** [comment]
Yes please. It must have been left over on the previous refactor. Thanks @gmertk!
