### ISSUE TITLE
Cannot find module @heroiclabs/nakama-js with NPM

### ISSUE THREAD

**Issue by ricky26** [heroiclabs/nakama-js#16]
Installing nakama-js with NPM results in a directory just containing the README, the package.json and the .gitignore.

The nakama-js module has a .gitignore with the dist/ directory in and I think since there's no .npmignore it falls back to using that to filter which files get installed.

**Comment by novabyte** [comment]
@ricky26 Thanks for the report. It'd be great to receive a PR for the fix if you're interested?

**Comment by ricky26** [comment]
@novabyte okay, I've opened PR #17.

**Comment by novabyte** [comment]
For simpler integration into various JS-based projects we've opted to keep build output in the "dist" folder in the repo.
