### ISSUE TITLE
Socket connection disconnects immediately on mobile

### ISSUE THREAD

**Issue by nudejsio** [heroiclabs/nakama-js#187]
Hi guys!

![Ekran Resmi 2024-03-11 12 19 31](https://github.com/heroiclabs/nakama-js/assets/91838363/bfbbda93-114a-428a-b07a-4a0cbe85877d)

**I got the above error from the browserstack emulator, so actually the network socket data on an iPhone device is like this.**

**Error message:** 
The operation couldn’t be completed. Software caused connection abort

If I put the application in the background on mobile and open the application again after 10-15-20 seconds, the direct socket connection is disconnected and it gives the above error.

**My configuration settings are like this, but it does not see these values.**

socket.ping_period_ms = 60000
socket.pong_wait_ms = 75000
setHeartbeatTimeoutMs(60000)

**Comment by mofirouz** [comment]
This isn't a nakama-js issue; you should ask this question on the forum:

https://forum.heroiclabs.com

Additionally, this looks like your server crashed(?) or was misconfigured - which we cannot advise on custom deployments. If you are running on Heroic Cloud, please send an email to support@heroiclabs.com.
