### ISSUE TITLE
Typo in UnlinkRequest

### ISSUE THREAD

**Issue by maxie-max** [heroiclabs/nakama-js#20]
```function build_ ()``` should return ```{ unlink: { custom } }``` instead of ```return { link: { custom } }```

Refer to [Gist](https://gist.github.com/maxie-max/31a56fa78374cb0fee2a33d67add751d)

**Comment by novabyte** [comment]
@maxie-max This is solved. An example of how to unlink is in the new test suite.
https://github.com/heroiclabs/nakama-js/blob/master/test/client-link.test.js#L70
