### ISSUE TITLE
How to send invitation to friends to join a party ?

### ISSUE THREAD

**Issue by Laguigue** [heroiclabs/nakama-js#206]
Hello, here is my usecase:

My user is friend with another one.
My user create a party

`const party = await socket.createParty(true, 2);`

I got my friend id earlier via `const friends = await client.listFriends(session);`

Is there a way to send my friend an invitation to join the party i created, from the js client ?
I see functions that allow you to create, join, send data to a party but the documentation is not clear about how you can simply send notification to your friends to share the party ID so they can join. Does they have to be in a group first ?

Thank you for the help !

**Comment by mofirouz** [comment]
Please ask these questions on the forum. GitHub Issues are reserved for bugs and developmental discussions. Forum is located: https://forum.heroiclabs.com
