### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by maxie-max** [heroiclabs/nakama-js#21]
Any chance to add check for ```typeof self !== 'undefined' ? self : typeof window !== 'undefined' ? window : {}```
instead of ```typeof self !== 'undefined' ? self : window```
in line 468 - nakama-js.umd.js. 

I use server rendering and compiler is giving me trouble since code references “browser globals” like window...

**Comment by novabyte** [comment]
@maxie-max You closed the issue. We don't have isomorphic support in the JS client yet but did you find a solution?

**Comment by MindfulMe** [comment]
Hi, if you have this problem you are going to take [nakama-umd.js](https://github.com/heroiclabs/nakama-js/releases/download/v2.0.1/nakama-js.umd.js) from here and replace base64 encryption (especially btoa, atoa methods) with your custom ones
