### ISSUE TITLE
onmatchdata message does not have opCode field

### ISSUE THREAD

**Issue by nikitaosyak** [heroiclabs/nakama-js#24]
contrary to what docs say [here](https://heroiclabs.com/docs/gameplay-multiplayer-realtime/#receive-data-messages), data object I receive does not have opCode field

layout of the object that I receive is as follows: 
![](https://i.gyazo.com/8938e239171f30c47c06f2853f2c4436.png)

**Comment by novabyte** [comment]
@nikitaosyak I think this is resolved. Let me know if it's an issue still and re-open please. 👍
