### ISSUE TITLE
nakama-js client error in Cocos Creator building for the Facebook Instant Games platform

### ISSUE THREAD

**Issue by comontes** [heroiclabs/nakama-js#28]
Using nakama-js.umd.js (v0.4.0) as a plugin script in Cocos Creator 1.9.1 causes a fail at building for Facebook Instant Platform. 

Steps to replicate:

1. Create new project on Cocos Creator
<img width="266" alt="captura de pantalla 2018-04-28 a la s 14 27 30" src="https://user-images.githubusercontent.com/1701089/39399215-509624b6-4af0-11e8-9f37-ab1d849caa42.png">
2. Drag and drop the "nakama-js.umd.js" file into the projects assets
<img width="211" alt="captura de pantalla 2018-04-28 a la s 14 20 30" src="https://user-images.githubusercontent.com/1701089/39399199-1800513a-4af0-11e8-97ea-e8822fad7e7e.png">
3. On properties panel of the "nakama-js.umd.js" file select "Import as Plugin"
<img width="309" alt="captura de pantalla 2018-04-28 a la s 14 20 34" src="https://user-images.githubusercontent.com/1701089/39399201-247a564a-4af0-11e8-9e6d-e41ac4cc8c6e.png">
4. Go to "Project" -> "Build..."
<img width="295" alt="captura de pantalla 2018-04-28 a la s 14 28 08" src="https://user-images.githubusercontent.com/1701089/39399225-6e64ba66-4af0-11e8-91ea-bc191772cfb6.png">
5. Select "Facebook Instant Games" as  platform.
6. Build:

<img width="1440" alt="captura de pantalla 2018-04-28 a la s 14 22 41" src="https://user-images.githubusercontent.com/1701089/39399190-de4d0bc2-4aef-11e8-83df-e7c8a797e57e.png">

---------------
With the esm version the build works but it gives this error running the project in development on Chrome:
<img width="658" alt="captura de pantalla 2018-04-28 a la s 15 07 40" src="https://user-images.githubusercontent.com/1701089/39399547-0de78532-4af6-11e8-81d9-622cd613608c.png">

---------------

With the cjs version gives the same error that umd version and it gives this error running the project in development on Chrome:
<img width="668" alt="captura de pantalla 2018-04-28 a la s 15 11 32" src="https://user-images.githubusercontent.com/1701089/39399570-89eed158-4af6-11e8-8032-6698fea6d1d5.png">

**Comment by novabyte** [comment]
@comontes Thanks for the detailed report. The new client code uses Rollup.js which builds compatible bundles for Cocos Creator. 👍
