### ISSUE TITLE
Typo in client.js

### ISSUE THREAD

**Issue by functorhk** [heroiclabs/nakama-js#3]
There is a typo in client.js in the line :
p.resolve({id: message.rcp.id, payload: message.rpc.payload});

The correct one should be:

p.resolve({id: message.rpc.id, payload: message.rpc.payload});

**Comment by novabyte** [comment]
@functorhk This was resolved in the 0.2.0 release (also available on NPM)

https://github.com/heroiclabs/nakama-js/releases/v0.2.0
