### ISSUE TITLE
btoa is undefined (atob is undefined)

### ISSUE THREAD

**Issue by MindfulMe** [heroiclabs/nakama-js#35]
### Problem:
Hi, if you have this problem you are going to take [nakama-umd.js](https://github.com/heroiclabs/nakama-js/releases/download/v2.0.1/nakama-js.umd.js) from here and replace base64 encryption (especially btoa, atoa methods) with your custom ones.
### Solution:
Here is the solution, it is rewritten nakama javascript library with replaced encryption methods (for v2.0.1).
For example:
[nakama-js.umd.js.zip](https://github.com/heroiclabs/nakama-js/files/2269868/nakama-js.umd.js.zip)

**Comment by novabyte** [comment]
@MindfulMe We should bundle a Base64 library already with the client (which is not encryption). I'll reopen the issue and check why it's not bundled correctly. It's probably an issue with how it's packaged.

**Comment by MindfulMe** [comment]
Okay, thanks for the correction @novabyte

**Comment by novabyte** [comment]
This is now resolved because we don't use `window.btoa` and `window.atob` at all (although its unclear why the polyfill library for it wasn't added properly to the build output). See f2edab14ac8e0bfb7eb9c6cdd5d6f9f846f4c896.

**Comment by dozgunyal** [comment]
Hi,
Is there a release plan for this?
This fix is not published.

**Comment by novabyte** [comment]
@dozgunyal We've had problems with various JavaScript build tools over time as we've maintained the client. It's currently in the middle of an overhaul so we've not done releases in a while. In the meantime you can import direct from GitHub.
