### ISSUE TITLE
issues with generatecid

### ISSUE THREAD

**Issue by Dimon4eg** [heroiclabs/nakama-js#39]
I'm trying to use nakama-js client in cocos2d-x project with java script.
Don't want not use outdated nakama C++ client and write bindings to use it in my js project.

original generatecid:
```js
DefaultSocket.prototype.generatecid = function () {
    return __spread(Array(30)).map(function () { return Math.random().toString(36)[3]; }).join('');
};
```

1) First issue with generatecid on native platforms where cocos uses spidermonkey as js engine.
The generatecid returns empty string and as result sockets doesn't work properly.
It seems Array.map doesn't iterate when elements are nulls.

2) Second issue - as `Math.random()` might return 0 in this case generatecid will return cid with "undefined" word inside. e.g. `20undefineddra7tl3k9iuzzwl78m2m87rduph`
Maybe this is not a problem. Just wanted to inform you.

I fixed the issues in following manner:

```js
DefaultSocket.prototype.generatecid = function () {
    var cid = "";
    for (var i=0; i < 30; ++i) {
        var s = Math.random().toString(36);

        if (s.length > 2)
            cid = cid.concat(s[3]);
        else
            cid = cid.concat(s[0]);
    }
    return cid;
};
```

P.S. My simple implementation works faster than original one by 15%. Tested on latest Chrome.

**Comment by Dimon4eg** [comment]
Also have question:
What scope of cid uniqueness?
Should be unique per client socket or globally for all clients?

**Comment by Dimon4eg** [comment]
Then next proposal: just use in socket counter: on generate convert it to string and return as cid and then increment. This will be the simplest and fast method.
What do you think?

**Comment by novabyte** [comment]
@Dimon4eg I'm not sure why we overcomplicated it with a UUID. A counter would work fine per socket object. Just a way for the server to respond to the client in a way the client can disambiguate. 👍

**Comment by Dimon4eg** [comment]
Great! Thanks for confirmation. Will send PR

**Comment by novabyte** [comment]
Awesome @Dimon4eg mark me as the reviewer for it 👍
