### ISSUE TITLE
Javascript - Sent messages with verbose logger are logged base64 encoded

### ISSUE THREAD

**Issue by JamesWright-slipstream** [heroiclabs/nakama-js#47]
When verbose logging is turned on all received messages are in plain text but sent messages are logged already encoded.

This could be fixed by putting the data into the message, logging it and then doing the encode. at the moment it logs at the end of the send method of default socket.

**Comment by jackunion** [comment]
@lugehorsam closed in https://github.com/heroiclabs/nakama-js/pull/157

**Comment by leokaplan** [comment]
is there a release planned or at least a workaround? this makes debugging quite annoying...
