### ISSUE TITLE
Nakama-js is no longer available on npm

### ISSUE THREAD

**Issue by brett-richardson** [heroiclabs/nakama-js#5]
I'm not sure if this is the right forum for this issue.

Currently `nakama-js` is not published on NPM which makes it a little difficult to manage, and may cause newcomers issues getting started with Nakama.

**Comment by novabyte** [comment]
@brett-richardson I've just investigated and I think it's all available as normal:
https://www.npmjs.com/package/@heroiclabs/nakama-js

I ran `yarn add @heroiclabs/nakama-js` on a skeleton project with `yarn init` and it all works. I'm actually about to complete a release for 0.2.0 and will drop a note here as soon as it's available on NPM.

**Comment by novabyte** [comment]
@brett-richardson The 0.2.0 release is out (also available on NPM):

https://github.com/heroiclabs/nakama-js/releases/v0.2.0
https://www.npmjs.com/package/@heroiclabs/nakama-js
