### ISSUE TITLE
Encoding/Decoding Unicode Character

### ISSUE THREAD

**Issue by ale-sg** [heroiclabs/nakama-js#54]
The `socket.onmessage` method is incorrectly decoding strings with potential unicode characters. 
The `socket.send` method is incorrectly encoding strings with potential unicode characters.

The Unicode Problem - References
https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem
https://stackoverflow.com/a/30106551

**Comment by ale-sg** [comment]
The suggested fix:

https://github.com/heroiclabs/nakama-js/pull/55

**Comment by novabyte** [comment]
Thanks @ale-sg. Your contribution is now merged. See f2edab14ac8e0bfb7eb9c6cdd5d6f9f846f4c896.
