### ISSUE TITLE
authenticateFacebookInstantGame mixes up `username` and `create`

### ISSUE THREAD

**Issue by leoncarl** [heroiclabs/nakama-js#68]
https://github.com/heroiclabs/nakama-js/blob/master/src/client.ts#L794 `username` and `create` parameters are out of order.  Any call with `create: true` will in fact create a user with username = "true".  This means you can only create one user when using this authentication type as `username` needs to be uniq.

**Comment by lugehorsam** [comment]
Thanks for catching @leoncarl
