### ISSUE TITLE
Assuming window and fetch

### ISSUE THREAD

**Issue by TarSzator** [heroiclabs/nakama-js#7]
The client assumes it is running in a browser but since it is an npm registered package it should also run in node.

This can easily be archived by replacing window.console with 
```
typeof console !== 'undefined'
```

And usage of node-fetch if fetch is not available already

**Comment by novabyte** [comment]
@TarSzator Thanks for the feedback. I'll look at `node-fetch` and do feature detection before we log output.

**Comment by novabyte** [comment]
This is resolved in the [v0.4.0 release](https://github.com/heroiclabs/nakama-js/releases/v0.4.0). Thanks @TarSzator
