### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by TarSzator** [heroiclabs/nakama-js#8]
When requests are made via fetch
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

Which is not supported by all browsers!

There is no catch call to catch errors. Which leads to freezes in some situations

**Comment by novabyte** [comment]
This is resolved in the [v0.4.0 release](https://github.com/heroiclabs/nakama-js/releases/v0.4.0).
