### ISSUE TITLE
Add safety checks to postMessage usage

### ISSUE THREAD

**Issue by danfinlay** [heroiclabs/nakama-js#86]
This issue may have already been fixed, but opening it here because it was reported with us ~2 years ago.

Currently nakama uses iframes with `postMessage` to relay messages internally. Other scripts can also use the `postMessage` API, and currently nakama.js seems to be able to crash when another script posts a message that it doesn't recognize.

Nakama.js should do checks for the properties it expects on incoming messages.

Related to https://github.com/MetaMask/metamask-extension/issues/5533

**Comment by novabyte** [comment]
@danfinlay I don't think this issue applies because it's been years since we used the DOM API for `postMessage` to an IFrame.
