### ISSUE TITLE
Match listings in javascript SDK

### ISSUE THREAD

**Issue by mshanak** [heroiclabs/nakama-js#89]
I am trying to use the Match listings function in my javascript client, but it always returns an empty result without any errors or exceptions.
Following the code that I used:
```
let matches=this.client.listMatches(this.session);
```

Is there anything I am missing?

**Comment by lugehorsam** [comment]
@mshanak if you view the matches inside the Nakama 3.0 console, do you see any running matches? Are they authoritative?
