### ISSUE TITLE
Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by luesp15** [heroiclabs/nakama-js#92]
Hi there, 
I'm using **heroiclabs/nakama-js** v. 2.1.5.

I've included in my web page this js:
` <script src="nakama-js.iife.js"></script> `

Following the documentation I had no problems creating the client, but I have problems creating the session. More precisely on the console I get the following error:
_Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules_

My code is the following:
```
var client = new nakamajs.Client("defaultkey", "myserverIP", "7350", true);
const customId = "45678";
const session = await client.authenticateCustom(customId)
localStorage.nakamaAuthToken = session.token;

const useSSL = true;
const verboseLogging = true;
// Send presence events to subscribed users.
const createStatus = false;
const socket = client.createSocket(useSSL, verboseLogging);
session = await socket.connect(session, createStatus)

const channelId = "Room1";
const persistence = true;
const hidden = true;

var response = await socket.joinChat(channelId, 1, persistence, hidden);
console.info("Successfully joined channel:", response.channel.id);
```

**Comment by lugehorsam** [comment]
Hey @luesp15 :wave: 

I think we can take this error message at its face value. If you are running the code you have shown in the global javascript namespace then it is not occurring in either an async function or a module. 

If you move the `await` code to a function marked as `async` and then call that function from your code, that should work.

Alternatively you can use `.then()` promise syntax if you don't want to create a separate function.

**Comment by luesp15** [comment]
I have tried with the `.then()` but it is not functional in my situation.

While with `await` I was unable to get results.

Could you give me an example?
