### ISSUE TITLE
rpcHttpKey function not working correctly

### ISSUE THREAD

**Issue by MWFIAE** [heroiclabs/nakama-js#99]
Hi,

I noticed that the rpcHttpKey function in the client, calls the rpcFunc2 function without its first argument - the bearer token, which results in an invalid rpc call.

https://github.com/heroiclabs/nakama-js/blob/master/packages/nakama-js/client.ts#L1560

https://github.com/heroiclabs/nakama-js/blob/master/packages/nakama-js/api.gen.ts#L2951

**Comment by lugehorsam** [comment]
@MWFIAE thanks for catching this. I'll release a patch fix for this today. Note that `rpcHttpKey` still won't accept a bearer token or pass one to `rpcFunc2` because it's intended to allow the client to communicate with the server without the user authenticating.

**Comment by lugehorsam** [comment]
@MWFIAE this is now fixed in the latest release. Note the signature has changed -- you'll see the new signature in the type definitions. It's mostly just reordering the parameters and removing an optional.

**Comment by MWFIAE** [comment]
Worked like a charm, thank you @lugehorsam 🥳
